### ISSUE TITLE
Feedback for Mobile CRM 10.2.1 update

### ISSUE THREAD

**Issue by Morten-git** [SuperOfficeDocs/feedback#113]
[Enter feedback here]
I think this is actually Mobile CRM version 10.2.7 (ref https://community.superoffice.com/en/product-releases/release-notes/release-details/?release=Mobile_CRM_10.2.7)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [news-mobile-crm-10.2.1](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/release-notes/10.2/mobile/10.2.1-update.md/#L1)

**Comment by kirstiaa** [comment]
10.2.1 Mobile CRM is not correct, it is 10.2.7!

Updated 2 files
* 10.2.1-update.md for mobile | release-notes\10.2\mobile\10.2.1-update.md
* 10.2 index.md | release-notes\10.2\index.md

in 2 different pull requests, since I didn't find a place where I could add more than one file into one pull request.

**Comment by kirstiaa** [comment]
Branch:
#704 kirstiaa-patch-1
#705 kirstiaa-patch-2

**Comment by digitaldiina** [comment]
Was also missing changes in toc and 10.2/mobile/index.md

Combined all changes on a branch and squashed to main in commit 8ed6f3c224962c78d193f451e28c82d357d55aa7
