### ISSUE TITLE
Feedback for Register identity provider (domain name)

### ISSUE THREAD

**Issue by GeasFilip** [SuperOfficeDocs/feedback#47]
Hi
This link is broken:
At the end of the guide:

![2021-12-15 09_23_58-Register identity provider (domain name) _ SuperOffice Docs og 10 sider til – Ar](https://user-images.githubusercontent.com/68385736/146150228-04f4bc7a-e812-4c87-9285-b234f6a9e180.png)

https://community.superoffice.com/en/technical/forms/register-sub-idp/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [register_idp](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/identity-management/superid/howto/register-idp.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Thank-you for your comment. We are aware of this and currently tackling lots of URL changes due to the community's new web site and the changes that have occured. 

The URL you seek is now located 
Here: https://community.superoffice.com/register-sub-idp
and here: https://community.superoffice.com/en/technical/forms/online-services/register-idp-sub-domain/

The broken links on docs will be fixed with a day or two.

See issue #166 
https://github.com/SuperOfficeDocs/superoffice-docs/issues/166

**Comment by GeasFilip** [comment]
Hi. Thank you for the quick reply. Thought it could be related to recent changes, I was just about to send the guide to a customer so I noticed.

**Comment by SuperOfficeDevNet** [comment]
Docs have been updated with correct link.
