### ISSUE TITLE
Feedback for webhook

### ISSUE THREAD

**Issue by SuperDJ** [SuperOfficeDocs/feedback#62]
While on page https://docs.superoffice.com/api/netserver/webhooks/index.html or sub pages the menu is not opened. This makes it hard to navigate to the different webhook entities.
![image](https://user-images.githubusercontent.com/6484766/161495023-f8d5abfb-0523-468e-887d-9aba51ad53f4.png)
![image](https://user-images.githubusercontent.com/6484766/161495188-4bfddc6a-43f9-45dd-9b51-16c15290357e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [undefined](https://github.com/SuperOfficeDocs/data-access/blob/main/docs/netserver/webhooks/index.md/#L1)

**Comment by digitaldiina** [comment]
@SuperDJ webhooks have moved to automation: https://docs.superoffice.com/automation/webhook/index.html
You will find all the pages and their left-hand menu there. Sorry for the inconvenience.

![image](https://user-images.githubusercontent.com/23242792/161498720-7b9ab4e4-9419-41ba-b3bc-0a97b4412e1e.png)

**Comment by SuperDJ** [comment]
@digitaldiina found the https://docs.superoffice.com/api/netserver/webhooks/index.html URL by going to search and search for webhook:
![image](https://user-images.githubusercontent.com/6484766/161506325-15b4cf85-ea47-43dc-8039-4501d03df89a.png)

**Comment by SuperOfficeDevNet** [comment]
Hi @SuperDJ!

Thanks for the feedback!  💯  It seems our search engine index was out of date and we have since initiated a reindex and it's starting to correct itself. 

Still some sub-pages to get updated, but at least the correct main page is at the top now.

![image](https://user-images.githubusercontent.com/15157161/161546674-f228ebb8-e63c-46ce-9baf-8df7c58245fd.png)

👍 

Best regards!
