### ISSUE TITLE
Feedback for FindContact

### ISSUE THREAD

**Issue by AlexanderLeafet** [SuperOfficeDocs/feedback#91]
NumberOfSales does not work on FindContact provider.
Even though we specify it we don't get any data for this column in the returned dictionary.

Is this a new column?

// Alexander

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [FindContact](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/api/archive-providers/reference/findcontact.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
In addition to fields that start with `saintstatus`, the following are SAINT counter columns: 

* numberofactivities
* numberofactivitiesinperiod
* numberofnotcompletedactivities
* numberofnotcompletedactivitiesinperiod
* lastactivity
* lastcompletedactivity
* lastdobyactivity
* numberofsales
* numberofsalesinperiod
* numberofnotcompletedsales
* numberofnotcompletedsalesinperiod
* lastsale
* lastcompletedsale
* lastdobysale

The saint counters are restriction-only columns. Meaning, you can't actually fetch their values, only use them as restrictions. That's not obvious 😳 but it is by design.

**Comment by AlexanderLeafet** [comment]
Thanks for the reply. Is it possible to make a request for fetching the value for this field??
//Alex

**Comment by SuperOfficeDevNet** [comment]
> Is it possible to make a request for fetching the value for this field??

Use one of the Sale providers with an [aggregate function](https://docs.superoffice.com/api/netserver/archive-providers/data-aggregation.html).
